Improved crash recovery testing & handling, script updates

diff --git a/homedir_scripts/gomd b/homedir_scripts/gomd
--- a/homedir_scripts/gomd
+++ b/homedir_scripts/gomd
@@ -2,9 +2,10 @@
 
 # For the BASEDIR, either specifying -opt or -dbg is fine, the script will auto-compute the other directory
 # A single opt or dbg workdir instance will tend to take 0.4-0.8 GB of space
-BASEDIR=/test/MDEV-16329_bb-11.0-oalter_MD210223-mariadb-11.0.1-linux-x86_64-opt
-RUNSOPT=2
-RUNSDBG=2
+BASEDIR=/test/MD180223-mariadb-11.0.1-linux-x86_64-opt
+#BASEDIR=/test/MDEV-16329_bb-11.0-oalter_MD210223-mariadb-11.0.1-linux-x86_64-opt
+RUNSOPT=4
+RUNSDBG=0
 #CONF=pquery-run-MD-spider.conf
 #CONF=pquery-run-MD-spider-all.conf
 #CONF=pquery-run-MD-federated.conf
@@ -63,14 +64,22 @@ for RUN in $(seq 1 ${TOTALRUNS}); do
           echo "Assert: ./${DIREND} should exist, based on directory passed by gomd_helper (${DIR})"
           exit 1; break
         else
-          if [ ! -r ~/sge ]; then 
-            echo "Assert: ~/sge not available! Cannot start pquery-go-expert!" 
-            exit 1; break
+          if [[ "${CONF}" != *"crt"* && "${CONF}" != *"CRT"* ]]; then  # Do not stat ge instances for crash recovery runs
+            if [ ! -r ~/sge ]; then 
+              echo "Assert: ~/sge not available! Cannot start pquery-go-expert!" 
+              exit 1; break
+            else
+              ~/sge "${DIREND}" "pr${RUN}"
+              TYPE="DBG"
+              if [ ${RUN} -le ${RUNSOPT} ]; then TYPE="OPT"; fi
+              echo "MD ${TYPE} Run ${RUN} started (Dir: ${DIR} Screen: pr${RUN}), and pquery-go-expert started for the same!"
+              MON[RUN]="$(echo "${DIR}" | sed 's|.*/||' | grep -o '[0-9]\+')"
+              break
+            fi
           else
-            ~/sge "${DIREND}" "pr${RUN}"
             TYPE="DBG"
             if [ ${RUN} -le ${RUNSOPT} ]; then TYPE="OPT"; fi
-            echo "MD ${TYPE} Run ${RUN} started (Dir: ${DIR} Screen: pr${RUN}), and pquery-go-expert started for the same!"
+            echo "MD ${TYPE} Run ${RUN} started (Dir: ${DIR} Screen: pr${RUN})!"
             MON[RUN]="$(echo "${DIR}" | sed 's|.*/||' | grep -o '[0-9]\+')"
             break
           fi
