crash recovery testing improvements

diff --git a/homedir_scripts/gomd b/homedir_scripts/gomd
--- a/homedir_scripts/gomd
+++ b/homedir_scripts/gomd
@@ -2,15 +2,15 @@
 
 # For the BASEDIR, either specifying -opt or -dbg is fine, the script will auto-compute the other directory
 # A single opt or dbg workdir instance will tend to take 0.4-0.8 GB of space
-BASEDIR=/test/MD180223-mariadb-11.0.1-linux-x86_64-opt
+BASEDIR=/test/MD270223-mariadb-11.0.2-linux-x86_64-opt
 #BASEDIR=/test/MDEV-16329_bb-11.0-oalter_MD210223-mariadb-11.0.1-linux-x86_64-opt
-RUNSOPT=4
+RUNSOPT=7
 RUNSDBG=0
 #CONF=pquery-run-MD-spider.conf
 #CONF=pquery-run-MD-spider-all.conf
 #CONF=pquery-run-MD-federated.conf
 #CONF=pquery-run-MD.conf  # Using PRE_SHUFFLE_SQL=2
-CONF=pquery-run-MD-crt.conf  # Using PRE_SHUFFLE_SQL=2
+CONF=pquery-run-MD-crt.conf
 #CONF=pquery-run-MD-allb.conf
 
 #CONF=pquery-run-MD-btrfs.conf
@@ -77,11 +77,17 @@ for RUN in $(seq 1 ${TOTALRUNS}); do
               break
             fi
           else
-            TYPE="DBG"
-            if [ ${RUN} -le ${RUNSOPT} ]; then TYPE="OPT"; fi
-            echo "MD ${TYPE} Run ${RUN} started (Dir: ${DIR} Screen: pr${RUN})!"
-            MON[RUN]="$(echo "${DIR}" | sed 's|.*/||' | grep -o '[0-9]\+')"
-            break
+            if [ ! -r ~/crc ]; then
+              echo "Assert: ~/crc not available! Cannot start crash recovery handlers!" 
+              exit 1; break
+            else
+              screen -admS "crc$(echo "${DIR}" | sed 's|.*/||')" bash -c "cd ${DIR}; while true; do ~/crc; sleep 20; done; bash"  # Start crash testing handler for the (each) workdir
+              TYPE="DBG"
+              if [ ${RUN} -le ${RUNSOPT} ]; then TYPE="OPT"; fi
+              echo "MD ${TYPE} Run ${RUN} started (Dir: ${DIR} Screen: pr${RUN}), and a crash recovery handler (~/crc) started for the same!"
+              MON[RUN]="$(echo "${DIR}" | sed 's|.*/||' | grep -o '[0-9]\+')"
+              break
+            fi
           fi
         fi 
       fi
