Bug and script updates

diff --git a/homedir_scripts/gomd b/homedir_scripts/gomd
--- a/homedir_scripts/gomd
+++ b/homedir_scripts/gomd
@@ -9,15 +9,20 @@ BASEDIR=/test/MD140222-mariadb-10.9.0-linux-x86_64-dbg
 #MDEV-25440-MD210122-mariadb-10.4.22-linux-x86_64-dbg
 #MD190122-mariadb-10.8.0-linux-x86_64-dbg
 #MD211221-mariadb-10.8.0-linux-x86_64-preview-10.8-MDEV-10654-inout-params-dbg
-RUNSOPT=5
-RUNSDBG=5
-#CONF=pquery-run-MD-spider.conf
-CONF=pquery-run-MD.conf  # File name only, no spaces, no directories
+RUNSOPT=7
+RUNSDBG=7
+CONF=pquery-run-MD-spider.conf
+#CONF=pquery-run-MD.conf  # File name only, no spaces, no directories
 #CONF=pquery-run-MD-buf.conf
 #CONF=pquery-run-MD-rr.conf
 #CONF=pquery-run-MD-idb1.conf
 #CONF=pquery-run-MD105-MT.conf
 #CONF=pquery-run-MD-SAN.conf
+
+if [ -z "${CONF}" ]; then
+  echo "\$CONF was not set. Please point it to a pquery-run.conf file like pquery-run-MD.conf (path is not required)"
+  exit 1
+fi
 
 if [ ! -d "${BASEDIR}" ]; then
   echo "Basedir: "${BASEDIR}" does not exist or is not readable by this script! Terminating."
