Bug updates, script updates

diff --git a/homedir_scripts/memory b/homedir_scripts/memory
--- a/homedir_scripts/memory
+++ b/homedir_scripts/memory
@@ -12,7 +12,20 @@ sudo bash -c "echo -1000 > /proc/$MYPID/oom_score_adj" || {
 # User variables
 DS_RUNONCE_EVERY=23  # Run ${HOME}/ds once every x loops, if present (run ~/mariadb-qa/linkit to install it if not). Set to 0 to disable ds being called
 KILL_PERCENT=7       # For example: 4: All processes using >=4% of memory will be killed
-FILTER="uniq_newbugs|large_newbug_run|findbug|bug_report|pquery-results|xargs|grep|timeout|build|fireworks|cc|clang|perl|mtr_to_sql|generator.sh|mysql-test-run|mtr|afl|bash|swapoff|swapon|clean_all|clean-all|memory|multirun"  # Filter this list of processes from termination
+
+# Filter this list of processes from termination
+# Call the process filter helper script to set the FILTER var
+SCRIPT_PWD=$(dirname $(readlink -f "${0}"))
+if [ -r "${SCRIPT_PWD}/mariadb-qa/process_filter.source" ]; then
+  source "${SCRIPT_PWD}/mariadb-qa/process_filter.source"
+elif [ -r "${SCRIPT_PWD}/process_filter.source" ]; then
+  source "${SCRIPT_PWD}/process_filter.source"
+elif [ -r "${HOME}/mariadb-qa/process_filter.source" ]; then
+  source "${HOME}/mariadb-qa/process_filter.source"
+else
+  echo "Assert: process_filter.source not found/readable by this script ($0)"
+  exit 1
+fi
 
 if [ "${STY}" == "" ]; then
   THIS_SCRIPT="$(readlink -f $0)"  # Resolves symlinks, result is the actual script including directory
