Major update of framework *SAN provisioning

diff --git a/homedir_scripts/myver b/homedir_scripts/myver
--- a/homedir_scripts/myver
+++ b/homedir_scripts/myver
@@ -1,4 +1,8 @@
 #!/bin/bash
+if [ ! -r bin/mysqld ]; then
+  echo "Assert: bin/mysqld not found!"
+  exit 1
+fi
 SOURCE_CODE_REV="$(grep -om1 --binary-files=text "Source control revision id for MariaDB source code[^ ]\+" bin/mysqld 2>/dev/null | tr -d '\0' | sed 's|.*source code||;s|Version||;s|version_source_revision||')"
 SERVER_VERSION="$(bin/mysqld --version | grep -om1 '[-0-9\.]\+-MariaDB' | sed 's|-MariaDB||')"
 LAST_THREE="$(echo "${PWD}" | sed 's|.*\(...\)$|\1|')"
