Bug updates, script improvements

diff --git a/homedir_scripts/tt b/homedir_scripts/tt
--- a/homedir_scripts/tt
+++ b/homedir_scripts/tt
@@ -65,17 +65,23 @@ fi
 echo "----- Bug String  -----"
 echo "${TEXT}"
 
+if [ -z "$(echo "${TEXT}" | sed 's|[ \t]||g')" ]; then
+  exit 1
+fi
 echo "----- String Scan -----"
 FRAMEX="$(echo "${TEXT}" | sed 's/.*|\(.*\)|.*|.*|.*$/\1/')"
 OUT="$(grep -Fi --binary-files=text "${TEXT}" ~/mariadb-qa/known_bugs.strings)"
 OUT2="$(grep -Fi --binary-files=text "${FRAMEX}" ~/mariadb-qa/known_bugs.strings)"
 if [ -z "${OUT}" ]; then
   if [ -z "${OUT2}" ]; then 
-    echo "BUG NOT FOUND IN KNOWN BUGS LIST! POTENTIALLY NEW BUG; SEARCH FIRST:"
+    echo "BUG NOT FOUND IN KNOWN BUGS LIST! POTENTIALLY NEW BUG TO LOG; SEARCH FIRST:"
   else 
-    echo "BUG NOT FOUND (IDENTICALLY) IN KNOWN BUGS LIST! HOWEVER, A PARTIAL MATCH BASED ON THE 1st FRAME ('${FRAMEX}') WAS FOUND, AS FOLLOWS: (PLEASE CHECK IT IS NOT THE SAME BUG):"
+    echo "BUG NOT FOUND (IDENTICALLY) IN KNOWN BUGS LIST! POTENTIALLY NEW BUG TO LOG. HOWEVER, A PARTIAL MATCH BASED ON THE 1st FRAME ('${FRAMEX}') WAS FOUND, AS FOLLOWS: (PLEASE CHECK IT IS NOT THE SAME BUG):"
     echo "${OUT2}"
   fi
+elif [[ "${OUT}" == "#"* ]]; then
+  echo "ALREADY KNOWN *PREVIOUSLY FIXED* BUG! POTENTIALLY NEW BUG TO LOG; SEARCH FIRST:"
+  echo "${OUT}"
 else
   echo "ALREADY KNOWN BUG!"
   echo "${OUT}"
